// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXEzZAzH7FgzNiLpfnd_HAqzb95FhkAvU',
    appId: '1:1050717853593:web:aee8ea73453e0ef874a508',
    messagingSenderId: '1050717853593',
    projectId: 'tentativa-bd-pg',
    authDomain: 'tentativa-bd-pg.firebaseapp.com',
    storageBucket: 'tentativa-bd-pg.appspot.com',
    measurementId: 'G-82WKKF2SQ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHVPCO5mPES1_EkNoy7dsJkAuoPw1K078',
    appId: '1:1050717853593:android:8dd5a46b1f50f43e74a508',
    messagingSenderId: '1050717853593',
    projectId: 'tentativa-bd-pg',
    storageBucket: 'tentativa-bd-pg.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARHNfFxhI52qpkTiahhNsaWZdC35bTK_Y',
    appId: '1:1050717853593:ios:5a0a4fc162d6882b74a508',
    messagingSenderId: '1050717853593',
    projectId: 'tentativa-bd-pg',
    storageBucket: 'tentativa-bd-pg.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARHNfFxhI52qpkTiahhNsaWZdC35bTK_Y',
    appId: '1:1050717853593:ios:d489010ca0cc199574a508',
    messagingSenderId: '1050717853593',
    projectId: 'tentativa-bd-pg',
    storageBucket: 'tentativa-bd-pg.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
